### PR TITLE
Use tracing for logging

### PR DESCRIPTION
**Pull request by Waelwindows**
**Don't merge this automatically**

This removes all need for the `log` module, as tracing provides better logging for async/normal programs.

However there's certain chocies that need to be taken first. As a primer I've decided to annotate every function that uses logging with the `#[instrument]` [attribute](https://docs.rs/tracing-attributes/0.1.9/tracing_attributes/attr.instrument.html). This has the fortunate/unforunate side-effect of printing the arguments, including self (which can be a bit long), with every logging event.

Of course, because of this I had to add `#[derive(Debug)]` to each struct that was used in logging.

Second of all, I've decided to use the [default](https://docs.rs/tracing-subscriber/0.2.10/tracing_subscriber/fmt/index.html) [`Subscriber`](https://tracing.rs/tracing/#subscribers) provided by [`tracing-subscriber`](https://crates.io/crates/tracing). Which may or may not suit your use cases.

### CODE REVIEW

**Comment by RipleyTom** [comment]
I changed the program to use tokio/async only recently so some features are from a primitive implementation I had before where 1 user = 1 thread.

I tested the PR quickly and several things:
-info! messages don't seem to get printed
-Loss of information, Client NPID is no longer getting printed on what used to be Client::log.

Log definitely needs to be changed to something more async but I personally think a simple mpsc is probably the way to go.
Ideally some macro/magic to avoid the log(&format!(...)) misery would be great but I have no idea if this is possible(while keeping the specificities of each log call, ie the Client(npid) part for client for example).

**Comment by Waelwindows** [comment]
About `info!()` being missing, are you sure you're setting `RUST_LOG` before the running the program ?
Here's how it looks like on my machine
```bash
$ RUST_LOG=trace cargo run
RPCN v0.3.0
Aug 02 03:15:35.654  INFO start{self=UdpServer { host: "0.0.0.0", signaling_infos: RwLock { data: {} }, join_handle: None }}: rpcn::server::udp_server: Now waiting for packets on <0.0.0.0:3657>
Server terminated with error: Failed to open certificate cert.pem
```
with trace on it should print every log. and I'm pretty sure that it should print NPIDs

**Comment by Waelwindows** [comment]
Managed to find a way to skip logging self when entering a new scope using `#[instrument]`.

What this means is that my previous example would turn into 
```
Aug 02 03:54:07.009  INFO start: rpcn::server::udp_server: Now waiting for packets on <0.0.0.0:3657>
Aug 02 03:54:07.011 TRACE mio::poll: registering with poller
Aug 02 03:54:07.012 TRACE mio::poll: registering with poller
Aug 02 03:54:07.012  INFO rpcn::server: Now waiting for connections on <0.0.0.0:31313>
```

**Comment by RipleyTom** [comment]
Turns out you were right that tracing was the best option for logging information. I went with a lighter implementation that didn't require instrumenting the structures but just uses a span to store information relevant to the session.

**Pull request closed without merging**
